Name:           ros-jade-visualization-msgs
Version:        1.12.5
Release:        0%{?dist}
Summary:        ROS visualization_msgs package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/visualization_msgs
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-message-runtime
Requires:       ros-jade-std-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-std-msgs

%description
visualization_msgs is a set of messages used by higher level packages, such as
rviz, that deal in visualization-specific data. The main messages in
visualization_msgs is visualization_msgs/Marker. The marker message is used to
send visualization &quot;markers&quot; such as boxes, spheres, arrows, lines,
etc. to a visualization environment such as rviz. See the rviz tutorial rviz
tutorials for more information.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Sep 30 2016 Tully Foote <tfoote@osrfoundation.org> - 1.12.5-0
- Autogenerated by Bloom

* Mon Feb 22 2016 Tully Foote <tfoote@osrfoundation.org> - 1.12.4-0
- Autogenerated by Bloom

* Mon Apr 20 2015 Tully Foote <tfoote@osrfoundation.org> - 1.12.3-0
- Autogenerated by Bloom

* Sat Mar 21 2015 Tully Foote <tfoote@osrfoundation.org> - 1.12.2-0
- Autogenerated by Bloom

* Tue Mar 17 2015 Tully Foote <tfoote@osrfoundation.org> - 1.12.1-0
- Autogenerated by Bloom

* Mon Dec 29 2014 Tully Foote <tfoote@osrfoundation.org> - 1.12.0-0
- Autogenerated by Bloom

